### ISSUE TITLE
Website downloads link for Debian broken

### ISSUE THREAD

**Issue by RobWilliamson1** [dave-theunsub/xkcd-generate#1]
Hi Dave, I tried to access the Debian "Downloads" link on the website and the link appears to be broken.  This link is the one I clicked on:   https://dave-theunsub.github.io/xkcd-generate/

Respectfully,
Robert Williamson

**Comment by dave-theunsub** [comment]
Hi Robert,

You're right; apparently I forgot to update the links.  In the meantime:

https://bitbucket.org/davem_/xkcd-generate/downloads/xkcd-generate_0.0.7-1_all.deb

The username changed, that's all.  Thanks for reporting it!  I'll fix it shortly.

respectfully,
Dave M

**Comment by dave-theunsub** [comment]
The links on that page should be fixed.  Closing for now.  Re-open with any other related issue, or start a new one.  Thanks for reporting.
